"""Alter user.alias to be unique

Revision ID: a4b211e205ac
Revises: dd3ab0aae0eb
Create Date: 2020-01-18 10:42:39.376689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b211e205ac'
down_revision = 'dd3ab0aae0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_alias', table_name='user')
    op.create_index(op.f('ix_user_alias'), 'user', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_alias'), table_name='user')
    op.create_index('ix_user_alias', 'user', ['alias'], unique=False)
    # ### end Alembic commands ###
